name: Push Docker image

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    environment: prod
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.vars.outputs.TAG }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: |
          echo "image_version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "image_name=stenioignacio/go-argocd" >> $GITHUB_ENV
          image_tag=$(git rev-parse --short HEAD)
          echo TAG=$image_tag >> $GITHUB_OUTPUT
          echo stenioignacio/go-argocd:$image_tag

      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: stenioignacio/go-argocd:${{env.image_version}}
          
  deploy_prod:
        name: Deploys to prod environment
        runs-on: ubuntu-latest
        environment: prod
        needs: [push_to_registry]
        steps:

        - name: Checkout the other repository
          uses: actions/checkout@v2
          with:
            repository: 'stenioignacio/go-docker-template-argocd' # replace with your repository
            token: ${{ secrets.PAT }} # use the PAT you saved as a secret
            path: 'go-docker-template-argocd' # this is the directory where the other repo will be checked out
            
        - name: Run sed on the other repository
          env:
            IMAGE_TAG: ${{ needs.push_to_registry.outputs.TAG }}
          run: |
            sed -i "/^ *image:/s|.*|  image: stenioignacio/go-argocd:$IMAGE_TAG|" ./go-docker-template-argocd/prd/helloworld-docker/helm/values.yaml
        - name: Commit and push changes
          run: |
            cd go-docker-template-argocd
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -am "Update version of helloworld-go image in prd"
            git push